### ISSUE TITLE
这代码都乱码了  //苦笑

### ISSUE THREAD

**Issue by reflyhight** [liangyangtao/sougou_login#1]
https://github.com/liangyangtao/sougou_login/blob/465e1c8cbe52cad9307c4b3781ef0b387763ef94/src/main/java/com/qizaodian/login/SogouLoginByHttpClient.java#L298

**Comment by liangyangtao** [comment]
这个不是错误
这就是问号和乱码
首先使用指定的编码，有时候返回的页面如果包含“多个问号“或 “乱码“ 就检查 meta 里的chaset ，重新toString 一下
